#!/bin/sh
sudo gem install bundler
echo "hook into nginx"
sudo ln -s /home/git/goodcodecrusader.git/nginx.conf /etc/nginx/sites-available/goodcodecrusader.conf
sudo ln -s /etc/nginx/sites-available/test-app.conf /etc/nginx/sites-enabled/goodcodecrusader.conf
echo "setup initial database"
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake db:seedq